name: Pre-commit

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      config:
        description: 'Path to the pre-commit config file.'
        type: string
        required: false
        default: '.pre-commit-config.yaml'

  workflow_call:
    inputs:
      config:
        description: 'Path to the pre-commit config file.'
        type: string
        required: false
        default: '.pre-commit-config.yaml'

env:
  PRE_COMMIT_CONFIG: ${{ inputs.config || '.pre-commit-config.yaml' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: |
            --all-files -c "$PRE_COMMIT_CONFIG"
