name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get auth token
        id: auth-token
        # uses: ./.actions/.github/actions/auth-token-action
        uses: stairwaytowonderland/actions/.github/actions/auth-token-action@v1
        with:
          app-private-key: ${{ secrets.ORG_REPO_USER_PRIVATE_KEY }}
          app-client-id: ${{ vars.ORG_REPO_USER_APP_ID }}

      - name: Semantic release
        id: release
        uses: stairwaytowonderland/node-semantic-release@main
        with:
          github-token: ${{ steps.auth-token.outputs.token }}

      - name: Dispatch Publish workflow
        if: steps.release.outputs.new-release-published == 'true'
        uses: ./
        with:
          workflow: publish.yaml
          tag: ${{ steps.release.outputs.new-release-git-tag }}
          fields: |
            notes-b64=${{ steps.release.outputs.new-release-notes-base64 }}
