name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT_CREATE_REPO }}

      - name: Semantic release
        id: release
        uses: stairwaytowonderland/node-semantic-release@main
        with:
          github-token: ${{ secrets.GH_PAT_CREATE_REPO }}

      - name: Dispatch Publish workflow
        if: steps.release.outputs.new-release-published == 'true'
        uses: ./
        with:
          workflow: publish.yaml
          tag: ${{ steps.release.outputs.new-release-git-tag }}
          fields: |
            notes-b64=${{ steps.release.outputs.new-release-notes-base64 }}
